spring:
  profiles:
    active: local

# Log Setting
logging:
  level:
    org.springframework.jdbc: debug
    hello.itemservice.repository.mybatis: trace
    org.hibernate.SQL: debug        # Hibernate가 생성하고 실행하는 SQL을 확인할 수 있다.
    org.hibernate.type.descriptor.sql.BasicBinder: trace   # SQL에 바인딩되는 파라미터를 확인할 수 있다.


# MyBatis
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
